language: ruby
rvm:
- 2.3.3

branches:
  only:
  - gh-pages

install:
  - gem install bundler jekyll

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - jekyll build

after_success:
  - zip -r looseleaf.zip _site

sudo: false # route your build to the container-based infrastructure for a faster build
